### ISSUE TITLE
mx_lca() with classes=2

### ISSUE THREAD

**Issue by mvarde12** [cjvanlissa/tidySEM#105]
Hello Dr. Van Lissa, 

After reading the paper, “Recommended Practices in Latent Class Analysis Using the Open-Source R-Package tidySEM” I was wondering if you could please clarify some questions?  
1.	When I run the mx_lca() function specifying classes=2, would you happen to know why the output from table_fit() provides information for one latent class, but the output from table_prob() provides information for two latent classes?  
2.	Is there a way to include participant ID numbers with the mx_lca() function, so I can use the latent classes as predictors in linear regression models? 

Thank you so much for your time!

**Comment by cjvanlissa** [comment]
Dear mvarde,

The fit table shows the fit for the whole model; you estimated one model (with two classes), so you get one row of fit info.

You can re-merge the class probabilities with the original dataset (they are in the same order), but as explained in the paper, you should not treat class membership as known in downstream analyses (unless the classification error is very low, e.g. entropy > .95). Otherwise, you can use the BCH() function, or pseudo_class()
